# R vs Python

## Opérateurs
Les opérations arithmétiques comme l'addition, la substraction, la multiplication, la division et l'exponentiation est pareil dans les deux languages.

In [1]:
sum = 1 + 3*4 + 5/2 + 2**2
print(sum)

19.5

Les opérateurs de comparaison sont aussi identiques.

In [5]:
res = 5 > 3
print(res)
print(res == False)
print(res != True)

True
False
False

## Data Types
**Rappel** : Pour créer une nouvelle variable sur R, on utilise `<-` pour désigner l'affection d'une variable.

mydata$sum <- mydata$x1 + mydata$x2

Sur Python, on utilise `=` pour affecter une variable. De plus, une variable n'est qu'un seul objet unique et ne peut contenir des sous-variables.

In [1]:
mydata1 = 5
mydata2 = 2

mydata_sum = mydata1 + mydata2
print(mydata_sum)

7

## Fonctions
Sur R et sur Python, on utilise couramment des fonctions. Par contre, elles sont écrites différements.

**Rappel** : Sur R, les fonctions ont cette allure:

function ( arglist ) {body}

Sur Python, une fonction est un bloc de code qui permet de découper un programme en plusieurs sous-programmes. Elle contient un nom, des paramètres (optionnels) et une valeur de retour (optionnelle).

In [10]:
def nom_de_ma_fonction(paramètres):
    # bloc d'instructions
    res = "Bonjour " + paramètres
    return res

In [11]:
# appel de la fonction
nom_de_ma_fonction("Christine")

'Bonjour Christine'

## Importer des données
**Rappel** : Pour importer des données dans R, il suffit d'écrire :

mydata <- read.table("c:/mydata.csv", header=TRUE, sep=",", row.names="id")

Pour importer des données d'un fichier CSV sur Python, il faut importer le module `csv`. Par exemple, pour la lecture d'un fichier CSV :

In [15]:
import csv

with open('./donnees/vitesse-debit.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    compteur = 0
    for row in csv_reader:
        print(row)

['Vitesses;Debits']
['42', '7051671941;1776', '95425958']
['43', '6154547408;1699', '67195265']
['34', '9989241038;1610', '4307984']
['41', '5380651072;1722', '07949174']
['37', '1662325983;1718', '75034319']
['96', '2914791402;1271', '29027315']
['96', '7394432187;1313', '60874659']
['99', '6190460222;1283', '43208834']
['94', '8982244729;1327', '90979287']
['31', '5619852743;1648', '82839893']
['104', '576707111;1207', '62755444']
['39', '1110967847;1745', '85920829']
['95', '8729547804;1351', '9053137']
['39', '8824526656;1646', '69487785']
['34', '5054524201;1724', '39190639']
['42', '7388361355;1722', '90429179']
['96', '90864262;1238', '78253683']
['96', '4946162467;1318', '86431514']
['41', '6285050163;1689', '37281357']
['101', '332167384;1244', '8005887']
['41', '8336894593;1749', '14395434']
['98', '7633984347;1324', '88222007']
['106', '688061186;1211', '926835']
['105', '09439933;1218', '08714141']
['47', '9264151748;1733', '09707581']
['99', '0237171956;1321', '36679248']
['42', '4861890733;1743', '42350341']
['97', '5414347408;1255', '37294309']
['101', '011321712;1316', '35097421']
['105', '05650405;1311', '73634998']
['40', '1726880834;1709', '41117538']
['31', '902366101;1592', '36872844']
['43', '2941523432;1733', '71130683']
['57', '230305125;1700', '57383916']
['100', '302072947;1381', '26255679']
['104', '731417987;1173', '02254092']
['99', '6706774341;1261', '76949339']
['48', '9267966203;1761', '14459805']
['96', '9896605634;1358', '03571015']
['98', '3281501323;1299', '0308402']
['52', '4709964619;1749', '14732982']
['38', '0852088933;1730', '93268265']
['97', '676393977;1283', '52058282']
['106', '032191491;1216', '83276002']
['105', '57181045;1208', '98710148']
['36', '9743107839;1730', '76950722']
['94', '6578456688;1348', '60183576']
['97', '9486257414;1275', '1760942']
['52', '6567777291;1819', '35725806']
['98', '6340293442;1284', '42176652']
['104', '647669582;1197', '69066518']
['113', '989604044;1115', '35651694']
['33', '9497992499;1663', '54011564']
['47', '0882463923;1682', '75502167']
['103', '790332915;1249', '91140582']
['103', '218991097;1216', '33086932']
['39', '8890446322;1734', '07113792']
['99', '8627427734;1188', '90795952']
['34', '507756163;1641', '4783499']
['47', '3969186751;1716', '5365256']
['99', '4925358248;1299', '01442125']
['41', '9204236442;1755', '04064367']
['102', '340636066;1221', '28239799']
['33', '5201492297;1617', '95945728']
['43', '0132302877;1722', '3594362']
['50', '35829035;1798', '86480844']
['37', '7837592024;1769', '50809784']
['97', '2455970198;1367', '22014775']
['39', '8238489636;1606', '88764776']
['37', '1792395884;1707', '78617921']
['100', '72726338;1256', '91336766']
['38', '0380662869;1699', '27323211']
['45', '8818831454;1795', '17644147']
['92', '7744049085;1301', '540147']
['103', '327118779;1194', '82377779']
['94', '4997093299;1362', '30440268']
['94', '850855933;1339', '67230854']
['99', '9342099867;1290', '99005645']
['39', '8793647474;1702', '19969897']
['31', '3078390772;1583', '30581851']
['47', '7440629236;1689', '96461958']
['102', '179193493;1216', '56055163']
['106', '047303903;1205', '66952724']
['96', '1105626869;1299', '46293655']
['98', '0976266436;1234', '61700849']
['98', '2032622647;1277', '54910009']
['35', '7274178286;1635', '54988166']
['94', '0242920216;1390', '63730433']
['105', '690869291;1181', '08671593']
['42', '389745955;1734', '34268591']
['34', '7522964929;1637', '92611776']
['95', '9507931567;1300', '2165688']
['98', '9307841957;1247', '93999232']
['53', '6764784751;1802', '09439249']
['92', '4796587264;1339', '45751402']
['96', '3352920561;1297', '60707419']
['58', '7952012117;1688', '61256933']
['99', '8096221305;1344', '68277075']
['95', '6873926715;1336', '91681288']
['21', '1413873461;1290', '94028043']
['102', '297346946;1291', '9737599']
['46', '4181839421;1779', '37728305']
['27', '0299268313;1581', '70713926']
['99', '8423672868;1302', '84636954']
['45', '2200477575;1672', '98314975']
['99', '509293678;1348', '78966253']
['49', '9438032531;1601', '1702964']
['48', '7485212836;1716', '72789173']
['95', '5114398702;1463', '20974668']
['37', '5595247735;1647', '91726486']
['98', '1054905208;1265', '25925797']
['108', '093130501;1169', '32114266']
['44', '1755605285;1724', '84422793']
['99', '6469506938;1268', '50970236']
['24', '6168240868;1393', '9460936']
['46', '3714116628;1770', '31501548']
['51', '582184191;1730', '17097386']
['99', '2156663751;1353', '68492009']
['98', '0196960281;1219', '17507999']
['27', '9931096576;1595', '00354594']
['95', '4676108668;1310', '46608919']
['91', '0522058934;1402', '60484021']
['53', '7314927696;1823', '27349316']
['37', '6957145155;1708', '96628212']
['100', '188871122;1277', '50986747']
['98', '415091087;1315', '14222363']
['29', '7993491399;1561', '61065688']
['27', '0533744917;1445', '24955626']
['89', '5276452794;1416', '54399642']
['91', '7407226868;1334', '46688578']
['91', '1425534722;1395', '14698881']
['40', '5573741447;1754', '87176034']
['104', '004456242;1237', '98488793']
['41', '9009154487;1618', '85972746']
['99', '2568790624;1349', '46922975']
['41', '2246639949;1656', '63193604']
['43', '0425802971;1787', '93809079']
['92', '741370332;1355', '50506344']
['35', '5969511255;1682', '7443731']
['96', '6739933411;1325', '73985833']
['102', '518645487;1292', '94155484']
['27', '3172653202;1495', '98846755']
['96', '5555296866;1207', '54879044']
['37', '6718754231;1695', '19613069']
['98', '1076432424;1286', '94325517']
['52', '4256791423;1790', '32827502']
['95', '3600265902;1262', '12805282']
['50', '2092092927;1730', '85134126']
['33', '7249048583;1695', '73534751']
['45', '6470847783;1671', '67927488']
['104', '046626952;1231', '67807308']
['90', '4639298434;1431', '08654668']
['35', '065936963;1635', '34638353']
['47', '8785883886;1784', '09698815']
['42', '4179300824;1783', '1989472']
['106', '307835619;1265', '85509614']
['41', '9609392829;1654', '2011746']
['25', '8915767595;1502', '008647']
['98', '8748229055;1327', '14749106']
['44', '1062339007;1716', '06557583']
['45', '3829149291;1757', '65853719']
['49', '1717748475;1777', '02481152']
['23', '6319995359;1507', '56305076']
['87', '9974693401;1423', '98112422']
['22', '4657888139;1413', '10948756']
['27', '9841715235;1527', '06224772']
['31', '8121757449;1622', '63246578']
['95', '7487695317;1363', '49456476']
['45', '0301064148;1725', '70772925']
['103', '980170983;1303', '36919238']
['47', '8522917828;1781', '74170531']
['42', '2761652968;1776', '20958003']
['26', '0836632402;1516', '45319531']
['94', '153573223;1249', '09086119']
['53', '7683382427;1670', '90102841']
['20', '7464471889;1235', '66797881']
['104', '631843778;1247', '6588704']
['97', '5274129976;1384', '29940305']
['31', '0424984426;1530', '34583846']
['95', '3636065091;1395', '96966855']
['106', '397509464;1261', '15276745']
['42', '051932046;1723', '48230087']
['35', '9481478702;1649', '00974333']
['103', '220957847;1237', '54888639']
['28', '9890925733;1616', '53537181']
['41', '5483225452;1750', '10914636']
['94', '3912122347;1331', '23327249']
['98', '425138649;1232', '05497155']
['102', '085276444;1220', '99065605']
['36', '6033986871;1729', '69123765']
['41', '5144323538;1711', '33931289']
['104', '592241839;1253', '37530533']
['102', '204046764;1288', '01194748']
['48', '9726506041;1765', '98162232']
['44', '8579673278;1916', '92009461']
['103', '385717077;1297', '6327886']
['33', '2357071288;1626', '23226515']
['41', '9545453574;1763', '47421235']
['100', '222109956;1264', '66864793']
['49', '691067995;1751', '55016404']
['91', '6492283466;1295', '49824317']
['99', '3680713118;1325', '13767389']
['22', '8129062612;1370', '96885221']
['102', '166820894;1223', '15890963']
['33', '6093901181;1580', '03882696']

Sur Python, il est aussi possible de lire un fichier CSV avec le module `pandas`. Par exemple :

In [14]:
import pandas as pd
pd.read_csv('./donnees/vitesse-debit.csv')

                     Vitesses;Debits
42  7051671941;1776         95425958
43  6154547408;1699         67195265
34  9989241038;1610          4307984
41  5380651072;1722          7949174
37  1662325983;1718         75034319
...                              ...
91  6492283466;1295         49824317
99  3680713118;1325         13767389
22  8129062612;1370         96885221
102 166820894;1223          15890963
33  6093901181;1580          3882696

[205 rows x 1 columns]

## Données statistiques